---
name: ./config/environment
namespace:
  - EvernoteLoginController
  - LoginController
  - NotebooksController
  - NotesController
  - UsersController
  - VisitorsController
  - User
  - Note
  - Notebook
  - EvernoteClient
  - CreateAdminService
  - AbstractSync
  - NoteSync
  - NotebookSync
  - ApplicationHelper
