# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e904786d8a4cfc803a20dd75de5eb0d4e55b4a3a4580ffaeb1006582a0befe8a81b5b9f962922d3db283db5622326de1c419b87e43bb25899d7aeaad9f6c8f66

test:
  secret_key_base: 0e2bdcff4cdceba2576306f904e6297a6bece40c5605c7d1806b698f029226c6024dadfa92686a33b05a4d31ac93c112a0f31dece3598b624435182035282ba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
